# Generated by Django 5.0.6 on 2024-05-28 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Blog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "heading",
                    models.CharField(
                        help_text="Придумайте заголовок статьи",
                        max_length=150,
                        verbose_name="Заголовок",
                    ),
                ),
                (
                    "slag_blog",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="slag"
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        help_text="Введите текст статьи", verbose_name="Текст статьи"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="blog",
                        verbose_name="Изображение",
                    ),
                ),
                (
                    "create_date",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Дата"
                    ),
                ),
                (
                    "published",
                    models.BooleanField(default=False, verbose_name="Опубликовано"),
                ),
                (
                    "view_counter",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество просмотров"
                    ),
                ),
            ],
        ),
    ]
