# Generated by Django 5.0.6 on 2024-06-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blog_options_alter_blog_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="create_date",
            field=models.DateTimeField(
                auto_now_add=True, default="2024-05-31", verbose_name="Дата"
            ),
            preserve_default=False,
        ),
    ]
