# Generated by Django 5.0.6 on 2024-06-03 19:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_blog_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="create_date",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата"
            ),
        ),
    ]
