# Generated by Django 5.0.6 on 2024-06-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0005_alter_blog_create_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="create_date",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата"),
        ),
    ]
