# Generated by Django 5.0.6 on 2024-05-26 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_remove_product_manufactured_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                auto_now_add=True, verbose_name="Дата последнего изменения"
            ),
        ),
    ]
