# Generated by Django 4.2 on 2024-06-30 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_product_is_published"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name", "category_name"],
                "permissions": [
                    ("Can published", "Может изменять статус публикации продукта")
                ],
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
    ]
